# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [23]:
# Your code here
import numpy as np
np.random.seed(0)
a = np.random.rand(3,3)
b = np.random.rand(3,3)
c = np.random.rand(3,3)

d = np.dot(a,(b+c))
e = np.dot(a,b)+np.dot(a,c)
a,b

(array([[0.5488135 , 0.71518937, 0.60276338],
        [0.54488318, 0.4236548 , 0.64589411],
        [0.43758721, 0.891773  , 0.96366276]]),
 array([[0.38344152, 0.79172504, 0.52889492],
        [0.56804456, 0.92559664, 0.07103606],
        [0.0871293 , 0.0202184 , 0.83261985]]))

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [16]:
# Your code here 
d = np.dot(a,(np.dot(b,c)))
e = np.dot(np.dot(a,b),c)
d,e

(array([[1.50645879, 1.63327163, 1.64109694],
        [1.16345859, 1.37398905, 1.27074845],
        [1.67193722, 1.91162206, 1.82927216]]),
 array([[1.50645879, 1.63327163, 1.64109694],
        [1.16345859, 1.37398905, 1.27074845],
        [1.67193722, 1.91162206, 1.82927216]]))

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [18]:
# Your code here 
d = np.dot(a,b)
e = np.dot(b,a)
d,e

(array([[0.66921566, 1.10867318, 0.84294166],
        [0.50586194, 0.83659006, 0.85606497],
        [0.75831917, 1.19135456, 1.09715043]]),
 array([[0.8732732 , 1.08130562, 1.25217138],
        [0.84717704, 0.86174093, 1.00868868],
        [0.4231782 , 0.81338747, 0.86794203]]))

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [24]:
# Your code here 
d = np.dot(np.transpose(a)),b
e = np.dot(np.transpose(b),a)
d,e

(array([[0.55808248, 0.94769875, 0.69331482],
        [0.59258766, 0.97639701, 1.15086269],
        [0.6819844 , 1.09454399, 1.167045  ]]),
 array([[0.55808248, 0.59258766, 0.6819844 ],
        [0.94769875, 0.97639701, 1.09454399],
        [0.69331482, 1.15086269, 1.167045  ]]))

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 